project:
  type: website
  output-dir: docs

website:
  title: "DGX Cluster Onboarding Guide"
  # navbar:
  sidebar:
    style: "docked"
    background: white
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Getting Started with the DGX Cluster"
        contents:
        - text: "Introduction to the DGX Cluster"
          href: notebooks/00_dgx.html
      - section: "Getting Started with Run:ai"
        contents:
        - text: "Login"
          href: notebooks/01_login.html
        - text: "Navigating the User Interface"
          href: notebooks/02_user_interface.html
      - section: "How-to Guides"
        contents:
        - text: "How to Use the Dashboards"
          href: notebooks/03_dashboards.html
        - text: "How to Manage Projects"
          href: notebooks/04_projects.html
        - text: "How to Configure Environments"
          href: notebooks/05_environments.html
        - text: "How to transfer data to/from the DGX Cluster"
          href: notebooks/07_data_transfer.html
  cookie-consent: 
    type: express
    style: simple
    palette: light
    policy-url: https://www.sydney.edu.au/privacy-statement.html
  google-analytics: "G-TNWWV3HK57"

  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"

format:
  html:
   link-external-newwindow: true
   link-external-icon: true # displays an icon next to external links
   toc: true
   theme:
      light: flatly
      # dark: darkly
  #  css: styles.scss
   code-link: true
   code-fold: false
   